"""init

Revision ID: 71b7d09121c1
Revises: 
Create Date: 2023-10-18 23:30:29.249215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b7d09121c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=4), nullable=False),
    sa.Column('post_type', sa.VARCHAR(length=3), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('link'),
    sa.UniqueConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
